services:
  spark:
    image: jupyter/pyspark-notebook
    volumes:
      - "./data:/home/jovyan/data:rw"
      - "./notebooks:/home/jovyan/notebooks:rw"
    ports:
      - "4040:4040"
      - "8888:8888"
    