GCP_CREDENTIALS_BLOCK = "gcp-credentials"
BIG_QUERY_BLOCK = "big-query"
BUCKET_BLOCK = "gcs-bucket"
SIM_FIM_API_KEY_BLOCK = "sim-fim-api-key"
DATASET_BLOCK = "dataset-name"
PROJECT_BLOCK = "project-name"